
language: python
python:
  - "3.6"

# install server dependencies
before_install:
  - "sudo apt-get install musl-dev g++ libgmp3-dev libmpfr-dev libmpc-dev gfortran liblapack-dev ca-certificates wget"
  - "pip install numpy"
  - "pip install scipy"
  - "wget https://dist.ipfs.io/go-ipfs/v0.4.10/go-ipfs_v0.4.10_linux-amd64.tar.gz"
  - "tar xvfz go-ipfs_v0.4.10_linux-amd64.tar.gz"
  - "./go-ipfs/ipfs init && ./go-ipfs/ipfs daemon &"

# install dependencies
install:
  - "pip install -r requirements.txt"
  - "python setup.py install"

# run tests
script:
  - pytest --flake8

notifications:
    slack: openmined:vOUE1d9jSb6V7R1r6zrjRD4E
